# Generated by Django 4.1.3 on 2022-12-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(),
        ),
    ]
